---
title: "glmmTMB repository"
date: "`r format(Sys.time(), '%d %b %Y')`"
---

To install binary packages from this repository, use

```{r eval=FALSE}
install.packages("glmmTMB",
                 repos = c("https://glmmTMB.github.io/glmmTMB/repos",
                           getOption("repos")["CRAN"]))
```

Available packages:

```{r pkgs, message=FALSE, echo =FALSE}
library(tidyverse)
all_f <- list.files(recursive = TRUE)
## get binaries

## fill in missing 'platform' for Windows/old MacOS
fix_val <- function(x) {
    if (length(x) == 4) {
        return(c(list(x[[2]], ""), x[3:4]))
    } else {
        return(x[-1])
    }
}
        
split_f <- all_f %>% grep(pattern = "bin", value=TRUE) %>%
    gsub(pattern = "(bin|contrib/)", replacement = "") %>%
    grep(pattern = "PACKAGES", value = TRUE, invert = TRUE) %>%
    strsplit("/") |>
    map(fix_val)


tbl <- (do.call(rbind, split_f)
    |> as_tibble(.name.repair="unique")
    |> setNames(c("os","platform","R_version","tmp"))
    |> separate(tmp, c("pkg", "pkg_ver"), sep = "_")
    |> mutate(across(pkg_ver, ~str_remove(., "\\.[a-z]+$")))
    |> arrange(desc(R_version), pkg, desc(pkg_ver))
)
```

```{r tbl, echo=FALSE, results="asis"}
knitr::kable(tbl)
```
