# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
# code generated according to https://deanattali.com/blog/migrating-travis-to-github/
# via usethis::use_github_action_check_standard()
# run in subdirectory:
#    https://stackoverflow.com/questions/57806624/github-actions-how-to-build-project-in-sub-directory
#  https://stackoverflow.com/questions/58139175/running-actions-in-another-directory
# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsworking-directory
# https://github.community/t/github-actions-working-directory-incorrectly-documented-unexpected-value-working-directory/16076
on:
  push:
    branches:
      - main
      - master
      - github_actions
  pull_request:
    branches:
      - main
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    if: "! contains(github.event.head_commit.message, '[skip ci]')"

    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, r: 'release'}
##          - {os: windows-latest, r: 'release'}
##          - {os: macOS-latest, r: 'release'}


    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      ## attempt to control over-parallelization
      OPENBLAS_NUM_THREADS: 1
      OMP_NUM_THREADS: 1

    steps:

      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: temporary github installs for archived pkgs
        run: |
          install.packages("remotes")
          remotes::install_github("leeper/prediction")
          remotes::install_github("leeper/margins")
          remotes::install_github("fsolt/dotwhisker")
        shell: Rscript {0}
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, dotwhisker=?ignore
          needs: check
          working-directory: ./glmmTMB
          upgrade: 'TRUE'
# https://github.com/lme4/lme4/issues/756

      - name: Install extra LaTeX packages
        if: runner.os == 'Linux'
        run: sudo apt-get install texlive-science texlive-latex-extra texlive-bibtex-extra
        working-directory: ./glmmTMB

      - uses: r-lib/actions/check-r-package@v2
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
          NOT_CRAN: true
        with:
          upload-snapshots: true
          working-directory: ./glmmTMB
